apiVersion: v1
kind: Service
metadata:
  name: social-feed-service
spec: 
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
      targetPort: 9376